FROM quay.io/centos-bootc/centos-bootc:stream9
COPY *.repo /etc/yum.repos.d/
RUN dnf --disablerepo='*' --enablerepo=copr-coreos-continuous --enablerepo=copr-rhcontainerbot-bootc -y distro-sync && \
    rpm -q composefs || dnf -y install composefs && \
    dnf clean all && rm -rf /var/* && \
    ostree container commit
